import { prepareRecognitionPhoto } from './image-fingerprint.js';

const API = location.pathname.startsWith('/instruments/') ? '/instruments/api' : '/api';
const input=document.getElementById('photoInput'), preview=document.getElementById('preview'), status=document.getElementById('status'), results=document.getElementById('results');
const token=sessionStorage.getItem('token');
async function call(path, options={}) { const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}); if(r.status===401) throw new Error('Сначала войдите в учёт оборудования'); if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'Ошибка сервера');} return r.json(); }
async function photo(id){const r=await fetch(`${API}/instruments/${id}/photo`,{headers:token?{Authorization:`Bearer ${token}`}:{}});return r.ok?URL.createObjectURL(await r.blob()):null;}
input.onchange=async()=>{const file=input.files?.[0];if(!file)return;results.innerHTML='';status.textContent='Подготавливаю фотографию…';try{const data=await prepareRecognitionPhoto(file);preview.src=data.dataUrl;preview.hidden=false;status.textContent='Сравниваю с фотобазой…';const found=await call('/recognition/search',{method:'POST',body:JSON.stringify({descriptors:data.descriptors})});if(!found.length){status.textContent='В фотобазе пока нет эталонных снимков.';return;}status.textContent=found[0].score>=.78?'Нашёл наиболее похожие приборы. Проверьте номер перед выдачей.':'Уверенного совпадения нет. Ниже — ближайшие варианты.';for(const item of found){const card=document.createElement('article');card.className='result';const pct=Math.max(0,Math.min(100,Math.round(item.score*100)));card.innerHTML=`<div class="no-photo"></div><div><h2>${esc(item.name)}</h2><p>${esc(item.model||'Модель не указана')}</p><p>Инв. № ${esc(item.inventory_no||'—')} · Серийный № ${esc(item.serial_number||'—')}</p><span class="score">Сходство ${pct}%</span></div><a class="open" href="./?id=${item.instrument_id}">Открыть карточку</a>`;results.appendChild(card);if(item.has_photo){const url=await photo(item.instrument_id);if(url)card.firstElementChild.outerHTML=`<img src="${url}" alt="">`;}}}catch(e){status.textContent=e.message;}finally{input.value='';}};
function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;}
