ALTER TABLE fm_users
  ADD COLUMN IF NOT EXISTS can_tools BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS can_db BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS can_cases BOOLEAN NOT NULL DEFAULT true;
